def COLOR_GREEN = "\u001b[42m"
def COLOR_RESET = "\u001b[0m"

def JENKINS_AGENT_NAME = "Motomo"
def GIT_REPO_URL = "https://github.com/Clanhouse/project-mechacrm.git"

node("${JENKINS_AGENT_NAME}") {
    timestamps {
        ansiColor('xterm') {
            try {

                stage('Cleaning workspace') {
                    echo "${COLOR_GREEN} Cleaning workspace ${COLOR_RESET}"
                    cleanWs()
                    sh 'env'
                    echo "Dir type is: ${PWD}"
                }

                stage('git clone') {
                    echo "${COLOR_GREEN} Git cloning ${COLOR_RESET}"
                    git url: "${GIT_REPO_URL}", branch: "${BRANCH_NAME}"
                }

                stage('npm install') {
                    echo "${COLOR_GREEN} Git cloning ${COLOR_RESET}"
                    echo "Dir type is: ${PWD}"
                    sh 'ls -la ./frontend'
                    sh 'docker run --rm -v ${PWD}/frontend/:/motomo -w /motomo node:lts-slim npm i'
                }

                stage('npm build') {
                    echo "${COLOR_GREEN} Git cloning ${COLOR_RESET}"
                    echo "Dir type is: ${PWD}"
                    sh 'docker run --rm -v ${PWD}/frontend/:/motomo -w /motomo node:lts-slim npm run build'
                    sh 'ls -la ./frontend/build'
                }

            } catch (Exception e) {
                echo "\u001b[41;1m Failed :( \u001b[0m\n"
            }
        }
    }
}
