CREATE TABLE IF NOT EXISTS customers (
	id      INT8 PRIMARY KEY NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY,
	name    VARCHAR(100)     NOT NULL,
	surname VARCHAR(100)     NOT NULL,
	phone   VARCHAR(30)      NOT NULL UNIQUE,
	address VARCHAR(255)     NOT NULL);
