spring:
  application:
    name: motomo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 7000
  servlet:
    context-path: /api

jwt:
  expiration: 3600000
  secret: secret

springdoc:
  swagger-ui:
    path: /documentation

allowedEndpoints:
  anonymous: /authenticate, /signup
  user: /hello
  admin: /hello
---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
